---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: samehbrdocker
    password: sameh2016

- name: Tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: samehbrdocker/devops
    tag: end
    push: yes